Layout movie details screen
achirkof/MovieApp pull request #1
Opened 2020-11-23 13:48 UTC by achirkof

Верстка экрана деталей фильма

![Screenshot_1606139048](https://user-images.githubusercontent.com/1292136/99969553-affa3500-2dab-11eb-966e-4502b3a4c4a3.png)

2020-11-25 09:03 UTC, froimsonm requested changes
В целом все очень даже прилично 👍 
Было бы круто как минимум избавиться от 3х лейаутов и оставить один
В идеале еще уменьшить иерархию вьюшек и будет вообще кайф

2020-11-25 09:03 UTC, froimsonm commented on app/src/main/AndroidManifest.xml
> +            android:resource="@array/preloaded_fonts" />
Круто, кайф! 👍

2020-11-25 09:03 UTC, froimsonm commented on app/src/main/java/com/achirkof/movieapp/MainActivity.kt
> +import android.view.WindowManager
Оно где-то используется?

2020-11-25 09:03 UTC, froimsonm commented on app/src/main/res/layout-v23/activity_main.xml
> +            app:layout_constraintTop_toTopOf="parent">
Нужен ли здесь фрейм лейаут? Кажется можно наложение картинок сделать в рамках одного констрейнт лейаута 🤔

2020-11-25 09:03 UTC, froimsonm commented on app/src/main/res/layout-v23/activity_main.xml
> +            app:layout_constraintTop_toTopOf="parent">
Здесь тоже появилась дополнительная вложенность, хотя констрейнт как раз должен решать эту проблему.
В целом обычно считается, что чем меньше иерархия вьюшек, тем легче оно будет работать

Было бы круто тут оптимизировать

2020-11-25 09:03 UTC, froimsonm commented on app/src/main/res/layout-v23/activity_main.xml
> +                    app:srcCompat="@drawable/ic_star" />
Как задание "Со звездочкой" можно вынести это в кастомную вьюшку, которой снаружи будет задаваться рейтинг от 1 до 5

2020-11-25 09:03 UTC, froimsonm commented on app/src/main/res/layout-v28/activity_main.xml
> +<ScrollView
хмммм.. а какую проблему мы тут решаем с помощью layout-v28? 🤔

2020-11-25 09:03 UTC, froimsonm commented on app/src/main/res/layout-v28/activity_main.xml
> +<ScrollView
В том смысле, что, почему бы не сделать все в рамках одного лейаута?

2020-11-28 12:43 UTC, achirkof commented on app/src/main/AndroidManifest.xml
> +            android:resource="@array/preloaded_fonts" />
Убрал лишние лейауты

2020-11-28 12:44 UTC, achirkof commented on app/src/main/java/com/achirkof/movieapp/MainActivity.kt
> +import android.view.WindowManager
Нет. Убрал

2020-11-28 12:44 UTC, achirkof commented on app/src/main/res/layout-v23/activity_main.xml
> +            app:layout_constraintTop_toTopOf="parent">
Да, не нужен. Убрал

2020-11-28 12:46 UTC, achirkof commented on app/src/main/res/layout-v23/activity_main.xml
> +                    app:srcCompat="@drawable/ic_star" />
Вынес ревью, карточки актёров и лейбл PG рейтинга в отдельные компоненты

2020-11-28 12:47 UTC, achirkof commented on app/src/main/res/layout-v28/activity_main.xml
> +<ScrollView
Студия сама предложила мне вынести отельные лейауты для более ранних версия андроид. Поставил версию 30 и убрал лишние лейауты

2020-11-28 13:02 UTC, achirkof commented on app/src/main/res/layout-v23/activity_main.xml
> +            app:layout_constraintTop_toTopOf="parent">
Переписал всё на ConstraintLayout

2020-11-28 13:03 UTC, merged